rtabmap:
  ros__parameters:
    stereo: false
    subscribe_depth: true
    subscribe_rgb: true
    frame_id: 'oak'                # Same base frame as rgbd_odometry
    approx_sync: true
    qos_image: 1
    qos_camera_info: 1
    qos_odom: 1

    queue_size: 5
    sync_queue_size: 5

    # --- Mapping mode (set IncrementalMemory to "false" + InitWMWithAllNodes
    # to "true" for pure localization on a previously saved map) ---
    Mem/IncrementalMemory: true
    Mem/InitWMWithAllNodes: false

    Rtabmap/DetectionRate: '1.0'   # Loop-closure detection at 2 Hz is plenty
    Grid/FromDepth: false
    Grid/CellSize: '0.10'
    Cloud/VoxelSize: '0.10'
    Cloud/MaxDepth: '4.0'

    wait_for_transform: 0.2

    RGBD/OptimizeFromGraphEnd: false
    Optimizer/GravitySigma: "0.3"
