#!/bin/bash
# Wire our custom Docker layer (Dockerfile.evtol) into isaac_ros_common's
# container build, then optionally build it.
#
# Needed because isaac_ros_common is a third-party clone that gitignores
# .isaac_ros_common-config, so that file cannot be version controlled with
# the rest of our code - a fresh workspace clone must regenerate it. Run
# this once per machine / after re-cloning isaac_ros_common:
#
#   bash src/slam_bridge/scripts/setup_isaac_container.sh          # write config
#   bash src/slam_bridge/scripts/setup_isaac_container.sh --build  # + build image
#
# After this, run_dev.sh builds/runs an isaac_ros_dev-aarch64 image with
# isaac_ros_visual_slam already installed - no per-container apt install.
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="$(cd "$SCRIPT_DIR/../../.." && pwd)"
ISAAC_SCRIPTS_DIR="$WORKSPACE_DIR/src/isaac_ros_common/scripts"
CONFIG_FILE="$ISAAC_SCRIPTS_DIR/.isaac_ros_common-config"

if [ ! -d "$ISAAC_SCRIPTS_DIR" ]; then
    echo "ERROR: $ISAAC_SCRIPTS_DIR not found - is isaac_ros_common cloned into src/?"
    exit 1
fi

# Both run_dev.sh and build_image_layers.sh source this from their OWN
# directory, so it has to sit next to them rather than at the repo root.
cat > "$CONFIG_FILE" <<'EOF'
# eVTOL ITA container config, sourced by run_dev.sh / build_image_layers.sh.
#
# GENERATED by src/slam_bridge/scripts/setup_isaac_container.sh - edit that
# script, not this file. Gitignored by isaac_ros_common, hence regenerated.

# Append our custom layer on top of NVIDIA's aarch64.ros2_humble image.
# Resolves to Dockerfile.evtol in the search dir below.
CONFIG_IMAGE_KEY=ros2_humble.evtol

# Where to find Dockerfile.evtol. Relative paths are resolved against this
# scripts/ dir, which keeps the Dockerfile in our own version-controlled
# repo instead of inside the third-party isaac_ros_common clone.
CONFIG_DOCKER_SEARCH_DIRS=(../../slam_bridge/docker)
EOF

echo "Wrote $CONFIG_FILE"

if [ "$1" == "--build" ]; then
    echo "Building isaac_ros_dev-aarch64 with the evtol layer..."
    # run_dev.sh would attach to an already-running container instead of
    # rebuilding, so invoke the image builder directly.
    "$ISAAC_SCRIPTS_DIR/build_image_layers.sh" \
        --image_key "$(uname -m).ros2_humble.evtol" \
        --image_name "isaac_ros_dev-$(uname -m)"
    echo
    echo "Done. Note a container started BEFORE this build keeps running the"
    echo "old image - stop it and re-run run_dev.sh to pick up the new one."
fi
